[general]
import = [ "~/.config/alacritty/nightfox.toml"]

[env]
term = "xterm-265color"

[window]
decorations = "None"
startup_mode = "Maximized"
title = "Terminal"

[font]
normal = { family = "JetBrainsMonoNL Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMonoNL Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMonoNL Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMonoNL Nerd Font", style = "Bold Italic" }
size = 18.0

[scrolling]
history = 10000
multiplier = 3
