[general]
import = [ "~/.config/alacritty/themes/themes/nightfox.toml"]

[window]
decorations = "None"
startup_mode = "Maximized"
title = "Terminal"

[font]
normal = { family = "JetBrainsMonoNL Nerd Font", style = "Medium" }
bold = { family = "JetBrainsMonoNL Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMonoNL Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMonoNL Nerd Font", style = "Bold Italic" }
size = 24.0

[colors.primary]
background = "#000000"
[colors.footer_bar]
background = "#29394f"
[colors.hints.end]
background = "#29394f"
[colors.selection]
background = "#2b3b51"
[colors.search.matches]
background = "#3c5372"
[colors.normal]
black = "#000000"
[colors.bright]
black = "#222f41"
