#!/usr/bin/env zsh

# XDG
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state/"
export XDG_CACHE_HOME="$HOME/.cache"

# editor
export EDITOR="nvim"
export VISUAL="nvim"

# zsh
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export HISTFILE="$ZDOTDIR/.zhistory"
export HISTSIZE=10000
export SAVEHIST=10000

# locales
export LANG="en_US.UTF-8"
export LC_CTYPE="en_US.UTF-8"
export LC_MESSAGES="en_US.UTF-8"
export LC_TIME="lt_LT.UTF-8"
export LC_NUMERIC="lt_LT.UTF-8"
export LC_MONETARY="lt_LT.UTF-8"
export LC_MEASUREMENT="lt_LT.UTF-8"
export LC_PAPER="lt_LT.UTF-8"
export LC_COLLATE="en_US.UTF-8"
export LC_NAME="lt_LT.UTF-8"
export LC_ADDRESS="lt_LT.UTF-8"
export LC_TELEPHONE="lt_LT.UTF-8"
export LC_IDENTIFICATION="en_US.UTF-8"

# lsmu development
export HOMEPATH="/home/simas/Documents/LSMU"
export ENVIRONMENT="Development"

# git
export GIT_CONFIG_GLOBAL="$XDG_CONFIG_HOME/git/config"

# python shit
export PYTHON_USER_BASE="$XDG_DATA_HOME/python"
export PATH="$PYTHON_USER_BASE/bin:$PATH"
export PATH="$PATH:$HOME/.local/bin"
export PYTHON_HISTORY=$XDG_STATE_HOME/python_history
export PYTHONPYCACHEPREFIX=$XDG_CACHE_HOME/python
export PYTHONUSERBASE=$XDG_DATA_HOME/python

# dotnet and c# stuff
export NUGET_PACKAGES="$XDG_CACHE_HOME"/NuGetPackages
export DOTNET_CLI_TELEMETRY_OPTOUT=1
export OMNISHARPHOME="$XDG_CONFIG_HOME/omnisharp"

# docker
export DOCKER_CONFIG="$XDG_CONFIG_HOME"/docker
export MACHINE_STORAGE_PATH="$XDG_DATA_HOME"/docker-machine

# node
export NVM_DIR="$HOME/.config/nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm
export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME/npm"
export NPM_CONFIG_CACHE="$XDG_CACHE_HOME/npm"

# steam
# export STEAM_HOME="$XDG_DATA_HOME/steam"
# export STEAM_CONFIG_HOME="$XDG_CONFIG_HOME/steam"
# export STEAM_DATA_HOME="$XDG_DATA_HOME/steam"
# export STEAM_RUNTIME="$XDG_DATA_HOME/steam/runtime"

# java
export _JAVA_OPTIONS=-Djava.util.prefs.userRoot="$XDG_CONFIG_HOME"/java

# discord
export DISCORD_USER_DATA_DIR="${XDG_DATA_HOME}"

# os specific
case "$(uname -s)" in
	Linux)
		# ssh
		export SSH_AUTH_SOCK="$XDG_RUNTIME_DIR/ssh-agent.socket"

		# gnupg
		export GNUPGHOME="$XDG_DATA_HOME/gnupg"

		# wget
		export WGETRC="$XDG_CONFIG_HOME/wgetrc"

		# opt applications
		export PATH="$PATH:/opt/nvim-linux-x86_64/bin"
		export PATH="$PATH:/opt/deadbeef/bin"
		export PATH="$PATH:/opt/JetBrains Rider-2024.3.5/bin"
		;;
	Darwin)
		# opt applications
		export PATH="$PATH:/opt/homebrew/bin"
		;;
esac
