#!/usr/bin/env zsh

# XDG
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"

# editor
export PATH="$PATH:/opt/nvim-linux-x86_64/bin"
export EDITOR="nvim"
export VISUAL="nvim"

# zsh
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export HISTFILE="$ZDOTDIR/.zhistory"
export HISTSIZE=10000 
export SAVEHIST=10000

# lsmu development
export HOMEPATH="/home/simas/Documents/LSMU"
export ENVIRONMENT="Development"

# git
export GIT_CONFIG_GLOBAL="$XDG_CONFIG_HOME/git/config"

# python shit
export PYTHON_USER_BASE="$XDG_DATA_HOME/python"
export PATH="$PYTHON_USER_BASE/bin:$PATH"
export PATH="$PATH:$HOME/.local/bin"

# rider and other c# stuff
export PATH="$PATH:/opt/JetBrains Rider-2024.3.5/bin"
export NUGET_PACKAGES="$XDG_DATA_HOME/nuget"
export DOTNET_CLI_HOME="$XDG_DATA_HOME/dotnet"
export DOTNET_ROOT="$XDG_DATA_HOME/dotnet"
export DOTNET_CLI_TELEMETRY_OPTOUT=1

# docker
export DOCKER_CONFIG="$XDG_CONFIG_HOME/docker"
export DOCKER_DATA_ROOT="$XDG_DATA_HOME/docker"

# node
export NVM_DIR="$HOME/.config/nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
export NPM_CONFIG_USERCONFIG="$HOME/.config/npm"

# steam
export STEAM_HOME="$XDG_DATA_HOME/steam"
export STEAM_CONFIG_HOME="$XDG_CONFIG_HOME/steam"
export STEAM_DATA_HOME="$XDG_DATA_HOME/steam"
export STEAM_RUNTIME="$XDG_DATA_HOME/steam/runtime"

# gnupg
export GNUPGHOME="$XDG_DATA_HOME/gnupg"
