#!/usr/bin/env zsh

# xdg
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"
export XDG_CACHE_HOME="$HOME/.cache"

# gtk
export GTK_THEME="Adwaita:dark"

# default apps
export EDITOR="nvim"
export VISUAL="nvim"
export BROWSER="librewolf"

# zsh
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export HISTSIZE=10000
export SAVEHIST=10000

# development
export HOMEPATH="/home/simas/documents/LSMU"
export ENVIRONMENT="Development"
export PATH="$PATH:$HOME/.local/bin"

# git
export GIT_CONFIG_GLOBAL="$XDG_CONFIG_HOME/git/config"

# python shit
export PYTHON_HISTORY="$XDG_STATE_HOME/python_history"
export PYTHONPYCACHEPREFIX="$XDG_CACHE_HOME/python"
export PYTHONUSERBASE="$XDG_DATA_HOME/python"

# dotnet and c# stuff
export NUGET_PACKAGES="$XDG_CACHE_HOME/NuGetPackages"
export DOTNET_CLI_TELEMETRY_OPTOUT=1
export OMNISHARPHOME="$XDG_CONFIG_HOME/omnisharp"
export DOTNET_CLI_HOME="$XDG_CACHE_HOME/dotnet"

# docker
export DOCKER_CONFIG="$XDG_CONFIG_HOME/docker"
export MACHINE_STORAGE_PATH="$XDG_DATA_HOME/docker-machine"

# node
export NVM_DIR="$XDG_DATA_HOME/nvm"
export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME/npm/npmrc"
export NPM_CONFIG_CACHE="$XDG_CACHE_HOME/npm"

# java
export _JAVA_OPTIONS=-Djava.util.prefs.userRoot="$XDG_CONFIG_HOME/java"

# discord
export DISCORD_USER_DATA_DIR="$XDG_DATA_HOME/discord"

# gnupg
export GNUPGHOME="$XDG_DATA_HOME/gnupg"

# wget
export WGETRC="$XDG_CONFIG_HOME/wgetrc"

# fucking rust
export CARGO_HOME="$XDG_DATA_HOME/cargo"

# go
export GOPATH="$XDG_DATA_HOME/go"
export GOMODCACHE="$XDG_CACHE_HOME/go/mod"

# os specific
case "$(uname -s)" in
	Linux)
		# ssh (https://wiki.archlinux.org/title/SSH_keys#Start_ssh-agent_with_systemd_user)
		export SSH_AUTH_SOCK="$XDG_RUNTIME_DIR/ssh-agent.socket"

		# opt applications
		export PATH="$PATH:/opt/deadbeef/bin"
		;;
	Darwin)
		# opt applications
		export PATH="$PATH:/opt/homebrew/bin:/opt/homebrew/share/zsh/site-functions"
		;;
esac
